Istikbal_Backend/Istikbal_Backend/Models/CategoryIn.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Istikbal_Backend.Models
{
    public class CategoryIn:BaseEntity
    {
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }
        public List<CategoryDest> CategoryDests { get; set; }
        public List<ProductCategoryIn> ProductCategoryIns { get; set; }

    }
}

Istikbal_Backend/Istikbal_Backend/Areas/Admin/Controllers/CategoryInController.cs
using Istikbal_Backend.DAL;
using Istikbal_Backend.Extensions;
using Istikbal_Backend.Helpers;
using Istikbal_Backend.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System;
using System.Threading.Tasks;

namespace Istikbal_Backend.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryInController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;


        public CategoryInController(AppDbContext appDbContext, IWebHostEnvironment env)
        {
            _context = appDbContext;
            _env = env;
        }

        public IActionResult Index()
        {
            List<CategoryIn> CategoryInList = _context.CategoryIns.Where(s => !s.IsDeleted).ToList();
            return View(CategoryInList);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CategoryIn db = _context.CategoryIns.Find(id);
            if (db == null) return NotFound();
            db.IsDeleted = true;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryIn CategoryIn)
        {
            if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
            {
                return View();
            }

            if (!CategoryIn.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "Sekil Formati secin");
            }

            if (CategoryIn.Photo.CheckSize(20000))
            {
                ModelState.AddModelError("Photo", "Sekil 20 mb-dan boyuk ola bilmez");
            }


            string filename = await CategoryIn.Photo.SaveFile(_env, "assets/img/Category");
            CategoryIn.ImageUrl = filename;
            CategoryIn.CreatedTime = DateTime.Now;

            _context.CategoryIns.Add(CategoryIn);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            CategoryIn CategoryIn = _context.CategoryIns.Find(id);
            if (CategoryIn == null)
            {
                return NotFound();
            }
            return View(CategoryIn);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int? id, CategoryIn CategoryIn)
        {
            if (id == null)
            {
                return NotFound();
            }


            CategoryIn db = _context.CategoryIns.Find(id);
            if (db == null)
            {
                return NotFound();
            }
            if (CategoryIn.Photo != null)
            {

                if (ModelState["Photo"].ValidationState == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                {
                    return View();
                }

                if (!CategoryIn.Photo.IsImage())
                {
                    ModelState.AddModelError("Photo", "Sekil Formati secin");
                }

                if (CategoryIn.Photo.CheckSize(20000))
                {
                    ModelState.AddModelError("Photo", "Sekil 20 mb-dan boyuk ola bilmez");
                }
                Helper.DeleteFile(_env, "assets/img/Category", db.ImageUrl);
                string filename = await CategoryIn.Photo.SaveFile(_env, "assets/img/Category");
                db.ImageUrl = filename;
            }
            else
            {
                db.ImageUrl = db.ImageUrl;
            }

            db.UpdatedTime = DateTime.Now;
            db.Name = CategoryIn.Name;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            CategoryIn CategoryIn = _context.CategoryIns.Where(b => !b.IsDeleted).FirstOrDefault(b => b.Id == id);
            if (CategoryIn == null)
            {
                return NotFound();
            }
            return View(CategoryIn);
        }


    }
}

Istikbal_Backend/Istikbal_Backend/Areas/Admin/Views/CategoryIn/Create.cshtml
@model CategoryIn
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body"> 
                        <form class="forms-sample" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input asp-for="Photo" class="form-control" placeholder="Photo">
                            </div>
                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            <a asp-area="admin" asp-controller="categoryin" asp-action="index" class="btn btn-light">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

Istikbal_Backend/Istikbal_Backend/Areas/Admin/Views/CategoryIn/Detail.cshtml
@model CategoryIn
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<a asp-controller="CategoryIn" asp-action="create" class="btn btn-success">Create</a>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Photo
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Updated time
                                </th>
                                <th>
                                    Delete
                                </th>
                                <th>
                                    Edit
                                </th>
                                <th>
                                    #
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            

                                <tr>
                                    <td class="py-1">
                                        <img src="~/assets/img/Category/@Model.ImageUrl" alt="image" />
                                    </td>
                                    <td>
                                        @Model.Name
                                    </td>
                                    <td>
                                        @Model.UpdatedTime.ToString("dd MM yyyy mm : ss")
                                    </td>
                                    <td>
                                        <a asp-controller="CategoryIn" asp-action="delete" asp-route-id="@Model.Id" class="btn btn-danger">Delete</a>

                                    </td>
                                    <td>
                                        <a asp-controller="CategoryIn" asp-action="edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
                                    </td>
                                    <td>
                                        <a asp-controller="CategoryIn" asp-action="index"   class="btn btn-success">Cancel</a>

                                    </td>
                                </tr>
                         
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Istikbal_Backend/Istikbal_Backend/Areas/Admin/Views/CategoryIn/Edit.cshtml
@model CategoryIn
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <form class="forms-sample" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input asp-for="Photo" class="form-control" placeholder="Photo">
                            </div>
                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" class="form-control" placeholder="Name">
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            <a asp-area="admin" asp-controller="categoryin" asp-action="index" class="btn btn-light">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

Istikbal_Backend/Istikbal_Backend/Areas/Admin/Views/CategoryIn/Index.cshtml
@model List<CategoryIn>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<a asp-controller="CategoryIn" asp-action="create" class="btn btn-success">Create</a>

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    Photo
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Created time
                                </th>
                                <th>
                                    Delete
                                </th>
                                <th>
                                    Edit
                                </th>
                                <th>
                                    Detail
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td class="py-1">
                                        <img src="~/assets/img/Category/@item.ImageUrl" alt="image" />
                                    </td>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        @item.CreatedTime.ToString("dd MM yyyy mm : ss")
                                    </td>
                                    <td>
                                        <a asp-controller="CategoryIn" asp-action="delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>

                                    </td>
                                    <td>
                                        <a asp-controller="CategoryIn" asp-action="edit" asp-route-id="@item.Id" class="btn btn-primary">Edit</a>
                                    </td>
                                    <td>
                                        <a asp-controller="CategoryIn" asp-action="detail" asp-route-id="@item.Id" class="btn btn-success">Detail</a>

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>